language:
  node_js
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
